STACK SEGMENT PARA STACK 'Stack'
DW 32 DUP (0)

STACK ENDS
DATASEG SEGMENT PARA 'Data'
FLDD DW 215
FLDE DW 125
FLDF DW ?
DATASEG ENDS
CODESEG SEGMENT PARA 'Code'
MAIN PROC FAR

ASSUME SS:STACK, DS:DATASEG CS:CODESEG
MOV AX, DATASEG ; set address of data
MOV DS, AX ; segment in DS
MOV AX, FLDD ; Move 0215 to AX
ADD AX, FLDE ; Add 0125 to AX
MOV FLDF, AX ; Store sum in FLDF
MOV AX, 4C00H ; End processing
INT 21H

MAIN ENDP ; End of Procedure
CODESEG ENDS ; End of Segment
END MAIN ; End of Program