.MODEL SMALL
.STACK 100
.DATA
	MSG1 DB "HELLO$" ; MSG1 DB 'H','E','L','L','O','$'
	MSG2 DB "ASSEMBLY"
	MSG3 DB "LANGUAGE$"
	MENU DB 0DH,0AH,"----- FOOD -----"
	     DB 0DH,0AH,"1.PIZZAS"
	     DB 0DH,0AH,"2.BUGERS"
	     DB 0DH,0AH,"3.EXIT$"
	NL   DB 0DH,0AH,"$"
.CODE
MAIN PROC
	MOV AX,@DATA
	MOV DS,AX
	
	;----- OUTPUT STRING : 09H
	MOV AH,09H
	LEA DX,MSG1
	INT 21H

	;----- NEWLINE
	MOV AH,02H
	LEA DX,NL
	INT 21H
	
	;----- OUTPUT STRING : 09H
	MOV AH,09H
	LEA DX,MSG2
	INT 21H

;----- NEWLINE
	MOV AH,02H
	LEA DX,NL
	INT 21H

	;----- OUTPUT STRING : 09H
	MOV AH,09H
	LEA DX,MENU
	INT 21H

;----- NEWLINE
	MOV AH,02H
	LEA DX,NL
	INT 21H

	MOV AH,4CH
	INT 21H

MAIN ENDP
END MAIN